---
- hosts:  local
  name:   a playbook to configure my work laptop
  connection: local

  roles:
    - firewall
    - myfiles
    - packages
    - libvirtd
    - httpd
    - openscap
    - create-libvirt-network

- name: echo VPN
  debug: "Need to install redhat-internal-cert-install and redhat-internal-NetworkManager-openvpn-profiles"

- name: echo YubiKey
  debug: "Need to configure YubiKey"
