---
- name: Enable Google Chrome Repository
  template:
    src: "../templates/google-chrome.repo.j2"
    dest: /etc/yum.repos.d/google-chrome.repo
  tags: packages

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - libvirt-client
    - virt-manager
    - virt-install
    - atom
    - google-chrome-stable
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - ansible
    - wget
  tags: packages
