---
- name: Create {{ libvirt_network_name }} network from Template
  template:
    src: "../templates/custom-network.xml.j2"
    dest: /etc/libvirt/qemu/networks/{{ libvirt_network_name }}.xml
    mode: 0644
  tags: laptop

- name: Define {{ libvirt_network_name }} network in LibVirt
  command: virsh net-define /etc/libvirt/qemu/networks/{{ libvirt_network_name }}.xml
  tags: laptop

- name: Start {{ libvirt_network_name }} network in LibVirt
  command: virsh net-start {{ libvirt_network_name }}
  tags: laptop

- name: Set {{ libvirt_network_name }} network to autostart
  command: virsh net-autostart {{ libvirt_network_name }}
  tags: laptop
