---
- name: Make OpenSCAP directory
  file:
    path: /home/{{ laptop_local_user }}/openscap
    state: directory
    mode: 0775
  tags: openscap


# This is from https://martin.preisler.me/2016/05/combine-scap-tailoring-file-and-datastream-into-a-single-file/
- name: Copy 'combine-tailoring.py' file
  copy:
    src: combine-tailoring.py
    dest: /home/{{ laptop_local_user }}/openscap
    mode: 0777
  tags: openscap

- name: GIT clone the OpenSCAP/scap-security-guide
  git:
    repo: https://github.com/OpenSCAP/scap-security-guide
    dest: /home/{{ laptop_local_user }}/openscap
    clone: no
  tags: openscap
